name:                aoc2022
version:             0.1.0.0
github:              "chvp/aoc2022"
license:             MIT
author:              "Charlotte Van Petegem"
maintainer:          "charlotte@vanpetegem.me"
copyright:           "2022 Charlotte Van Petegem"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/chvp/aoc2022#readme>

dependencies:
- base >= 4.7 && < 5
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  day01:
    main:                Main.hs
    source-dirs:         day01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022
  day02:
    main:                Main.hs
    source-dirs:         day02
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022
  day03:
    main:                Main.hs
    source-dirs:         day03
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022
  day04:
    main:                Main.hs
    source-dirs:         day04
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022
  day05:
    main:                Main.hs
    source-dirs:         day05
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022
  day06:
    main:                Main.hs
    source-dirs:         day06
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022
  day07:
    main:                Main.hs
    source-dirs:         day07
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022
  day08:
    main:                Main.hs
    source-dirs:         day08
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022
  day09:
    main:                Main.hs
    source-dirs:         day09
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022
  day10:
    main:                Main.hs
    source-dirs:         day10
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022
  day11:
    main:                Main.hs
    source-dirs:         day11
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022
  day12:
    main:                Main.hs
    source-dirs:         day12
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022
  day13:
    main:                Main.hs
    source-dirs:         day13
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022
  day14:
    main:                Main.hs
    source-dirs:         day14
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022
  day15:
    main:                Main.hs
    source-dirs:         day15
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022
  day16:
    main:                Main.hs
    source-dirs:         day16
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022
